name: m_scms
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.5
  provider: ^6.0.0
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  syncfusion_flutter_pdfviewer: ^32.2.7
  pdfx: ^2.9.2
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/wlc_logo.png"
  min_sdk_android: 21
